name: Release
on: [push]

jobs:
  test-go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - run: go test -json > results.json
      - uses: actions/upload-artifact@v4
        with:
          name: go-test-results
          path: results.json
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
          tags: mramsden/goeff-bot:latest
